//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace Personel_Bilgi_Sistemi.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PersonelBilgilerini_AlOperationCompleted;
        
        private System.Threading.SendOrPostCallback personel_kayitOperationCompleted;
        
        private System.Threading.SendOrPostCallback KisiDonduradOperationCompleted;
        
        private System.Threading.SendOrPostCallback KisiDondurtcOperationCompleted;
        
        private System.Threading.SendOrPostCallback KisiDondurpersOperationCompleted;
        
        private System.Threading.SendOrPostCallback KisiSilOperationCompleted;
        
        private System.Threading.SendOrPostCallback KisiGuncelleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Personel_Bilgi_Sistemi.Properties.Settings.Default.Personel_Bilgi_Sistemi_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PersonelBilgilerini_AlCompletedEventHandler PersonelBilgilerini_AlCompleted;
        
        /// <remarks/>
        public event personel_kayitCompletedEventHandler personel_kayitCompleted;
        
        /// <remarks/>
        public event KisiDonduradCompletedEventHandler KisiDonduradCompleted;
        
        /// <remarks/>
        public event KisiDondurtcCompletedEventHandler KisiDondurtcCompleted;
        
        /// <remarks/>
        public event KisiDondurpersCompletedEventHandler KisiDondurpersCompleted;
        
        /// <remarks/>
        public event KisiSilCompletedEventHandler KisiSilCompleted;
        
        /// <remarks/>
        public event KisiGuncelleCompletedEventHandler KisiGuncelleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PersonelBilgilerini_Al", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet PersonelBilgilerini_Al() {
            object[] results = this.Invoke("PersonelBilgilerini_Al", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void PersonelBilgilerini_AlAsync() {
            this.PersonelBilgilerini_AlAsync(null);
        }
        
        /// <remarks/>
        public void PersonelBilgilerini_AlAsync(object userState) {
            if ((this.PersonelBilgilerini_AlOperationCompleted == null)) {
                this.PersonelBilgilerini_AlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPersonelBilgilerini_AlOperationCompleted);
            }
            this.InvokeAsync("PersonelBilgilerini_Al", new object[0], this.PersonelBilgilerini_AlOperationCompleted, userState);
        }
        
        private void OnPersonelBilgilerini_AlOperationCompleted(object arg) {
            if ((this.PersonelBilgilerini_AlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PersonelBilgilerini_AlCompleted(this, new PersonelBilgilerini_AlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/personel_kayit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet personel_kayit(
                    string tc_kimlik_no, 
                    string ad, 
                    string soyad, 
                    string dogum_yeri, 
                    string dogum_tarihi, 
                    string cinsiyet, 
                    string uyruk, 
                    string unvan, 
                    string personel_no, 
                    string personel_no2, 
                    string ev_telefonu, 
                    string cep_telefonu, 
                    string e_posta, 
                    string il, 
                    string ilce, 
                    string adres, 
                    string personel_no3, 
                    string ise_giris_tarihi, 
                    string firma, 
                    string sube, 
                    string calistigi_birim, 
                    string sigorta_sicil_no, 
                    string personel_no4, 
                    string vergi_numarasi, 
                    string vergi_dairesi, 
                    string banka, 
                    string banka_subesi, 
                    string banka_hesap_no, 
                    string personel_no5, 
                    string ilkokul_adi, 
                    string ilkokul_baslama_tarihi, 
                    string ilkokul_mezun_olma_tarihi, 
                    string lise_adi, 
                    string lise_baslama_tarihi, 
                    string lise_mezun_olma_tarihi, 
                    string universite_adi, 
                    string bolumu, 
                    string uni_baslama_tarihi, 
                    string uni_mezun_olma_tarihi, 
                    string egitim_adi, 
                    string egitim_bilgi, 
                    string egitim_baslama_tarihi, 
                    string egitim_bitirme_tarihi, 
                    string personel_no6, 
                    string isten_ayrilma_nedeni, 
                    string isten_ayrilma_tarihi, 
                    string askerlik_durumu, 
                    string tecil_nedeni, 
                    string sakatlik_durumu, 
                    string medeni_durum, 
                    string cocuk_sayisi, 
                    string kan_grubu, 
                    string ehliyet, 
                    string kizlik_soyadi, 
                    string rapor_aldigi_gun_sayisi, 
                    string izinli_gun_sayisi, 
                    string servis_kullanimi) {
            object[] results = this.Invoke("personel_kayit", new object[] {
                        tc_kimlik_no,
                        ad,
                        soyad,
                        dogum_yeri,
                        dogum_tarihi,
                        cinsiyet,
                        uyruk,
                        unvan,
                        personel_no,
                        personel_no2,
                        ev_telefonu,
                        cep_telefonu,
                        e_posta,
                        il,
                        ilce,
                        adres,
                        personel_no3,
                        ise_giris_tarihi,
                        firma,
                        sube,
                        calistigi_birim,
                        sigorta_sicil_no,
                        personel_no4,
                        vergi_numarasi,
                        vergi_dairesi,
                        banka,
                        banka_subesi,
                        banka_hesap_no,
                        personel_no5,
                        ilkokul_adi,
                        ilkokul_baslama_tarihi,
                        ilkokul_mezun_olma_tarihi,
                        lise_adi,
                        lise_baslama_tarihi,
                        lise_mezun_olma_tarihi,
                        universite_adi,
                        bolumu,
                        uni_baslama_tarihi,
                        uni_mezun_olma_tarihi,
                        egitim_adi,
                        egitim_bilgi,
                        egitim_baslama_tarihi,
                        egitim_bitirme_tarihi,
                        personel_no6,
                        isten_ayrilma_nedeni,
                        isten_ayrilma_tarihi,
                        askerlik_durumu,
                        tecil_nedeni,
                        sakatlik_durumu,
                        medeni_durum,
                        cocuk_sayisi,
                        kan_grubu,
                        ehliyet,
                        kizlik_soyadi,
                        rapor_aldigi_gun_sayisi,
                        izinli_gun_sayisi,
                        servis_kullanimi});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void personel_kayitAsync(
                    string tc_kimlik_no, 
                    string ad, 
                    string soyad, 
                    string dogum_yeri, 
                    string dogum_tarihi, 
                    string cinsiyet, 
                    string uyruk, 
                    string unvan, 
                    string personel_no, 
                    string personel_no2, 
                    string ev_telefonu, 
                    string cep_telefonu, 
                    string e_posta, 
                    string il, 
                    string ilce, 
                    string adres, 
                    string personel_no3, 
                    string ise_giris_tarihi, 
                    string firma, 
                    string sube, 
                    string calistigi_birim, 
                    string sigorta_sicil_no, 
                    string personel_no4, 
                    string vergi_numarasi, 
                    string vergi_dairesi, 
                    string banka, 
                    string banka_subesi, 
                    string banka_hesap_no, 
                    string personel_no5, 
                    string ilkokul_adi, 
                    string ilkokul_baslama_tarihi, 
                    string ilkokul_mezun_olma_tarihi, 
                    string lise_adi, 
                    string lise_baslama_tarihi, 
                    string lise_mezun_olma_tarihi, 
                    string universite_adi, 
                    string bolumu, 
                    string uni_baslama_tarihi, 
                    string uni_mezun_olma_tarihi, 
                    string egitim_adi, 
                    string egitim_bilgi, 
                    string egitim_baslama_tarihi, 
                    string egitim_bitirme_tarihi, 
                    string personel_no6, 
                    string isten_ayrilma_nedeni, 
                    string isten_ayrilma_tarihi, 
                    string askerlik_durumu, 
                    string tecil_nedeni, 
                    string sakatlik_durumu, 
                    string medeni_durum, 
                    string cocuk_sayisi, 
                    string kan_grubu, 
                    string ehliyet, 
                    string kizlik_soyadi, 
                    string rapor_aldigi_gun_sayisi, 
                    string izinli_gun_sayisi, 
                    string servis_kullanimi) {
            this.personel_kayitAsync(tc_kimlik_no, ad, soyad, dogum_yeri, dogum_tarihi, cinsiyet, uyruk, unvan, personel_no, personel_no2, ev_telefonu, cep_telefonu, e_posta, il, ilce, adres, personel_no3, ise_giris_tarihi, firma, sube, calistigi_birim, sigorta_sicil_no, personel_no4, vergi_numarasi, vergi_dairesi, banka, banka_subesi, banka_hesap_no, personel_no5, ilkokul_adi, ilkokul_baslama_tarihi, ilkokul_mezun_olma_tarihi, lise_adi, lise_baslama_tarihi, lise_mezun_olma_tarihi, universite_adi, bolumu, uni_baslama_tarihi, uni_mezun_olma_tarihi, egitim_adi, egitim_bilgi, egitim_baslama_tarihi, egitim_bitirme_tarihi, personel_no6, isten_ayrilma_nedeni, isten_ayrilma_tarihi, askerlik_durumu, tecil_nedeni, sakatlik_durumu, medeni_durum, cocuk_sayisi, kan_grubu, ehliyet, kizlik_soyadi, rapor_aldigi_gun_sayisi, izinli_gun_sayisi, servis_kullanimi, null);
        }
        
        /// <remarks/>
        public void personel_kayitAsync(
                    string tc_kimlik_no, 
                    string ad, 
                    string soyad, 
                    string dogum_yeri, 
                    string dogum_tarihi, 
                    string cinsiyet, 
                    string uyruk, 
                    string unvan, 
                    string personel_no, 
                    string personel_no2, 
                    string ev_telefonu, 
                    string cep_telefonu, 
                    string e_posta, 
                    string il, 
                    string ilce, 
                    string adres, 
                    string personel_no3, 
                    string ise_giris_tarihi, 
                    string firma, 
                    string sube, 
                    string calistigi_birim, 
                    string sigorta_sicil_no, 
                    string personel_no4, 
                    string vergi_numarasi, 
                    string vergi_dairesi, 
                    string banka, 
                    string banka_subesi, 
                    string banka_hesap_no, 
                    string personel_no5, 
                    string ilkokul_adi, 
                    string ilkokul_baslama_tarihi, 
                    string ilkokul_mezun_olma_tarihi, 
                    string lise_adi, 
                    string lise_baslama_tarihi, 
                    string lise_mezun_olma_tarihi, 
                    string universite_adi, 
                    string bolumu, 
                    string uni_baslama_tarihi, 
                    string uni_mezun_olma_tarihi, 
                    string egitim_adi, 
                    string egitim_bilgi, 
                    string egitim_baslama_tarihi, 
                    string egitim_bitirme_tarihi, 
                    string personel_no6, 
                    string isten_ayrilma_nedeni, 
                    string isten_ayrilma_tarihi, 
                    string askerlik_durumu, 
                    string tecil_nedeni, 
                    string sakatlik_durumu, 
                    string medeni_durum, 
                    string cocuk_sayisi, 
                    string kan_grubu, 
                    string ehliyet, 
                    string kizlik_soyadi, 
                    string rapor_aldigi_gun_sayisi, 
                    string izinli_gun_sayisi, 
                    string servis_kullanimi, 
                    object userState) {
            if ((this.personel_kayitOperationCompleted == null)) {
                this.personel_kayitOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpersonel_kayitOperationCompleted);
            }
            this.InvokeAsync("personel_kayit", new object[] {
                        tc_kimlik_no,
                        ad,
                        soyad,
                        dogum_yeri,
                        dogum_tarihi,
                        cinsiyet,
                        uyruk,
                        unvan,
                        personel_no,
                        personel_no2,
                        ev_telefonu,
                        cep_telefonu,
                        e_posta,
                        il,
                        ilce,
                        adres,
                        personel_no3,
                        ise_giris_tarihi,
                        firma,
                        sube,
                        calistigi_birim,
                        sigorta_sicil_no,
                        personel_no4,
                        vergi_numarasi,
                        vergi_dairesi,
                        banka,
                        banka_subesi,
                        banka_hesap_no,
                        personel_no5,
                        ilkokul_adi,
                        ilkokul_baslama_tarihi,
                        ilkokul_mezun_olma_tarihi,
                        lise_adi,
                        lise_baslama_tarihi,
                        lise_mezun_olma_tarihi,
                        universite_adi,
                        bolumu,
                        uni_baslama_tarihi,
                        uni_mezun_olma_tarihi,
                        egitim_adi,
                        egitim_bilgi,
                        egitim_baslama_tarihi,
                        egitim_bitirme_tarihi,
                        personel_no6,
                        isten_ayrilma_nedeni,
                        isten_ayrilma_tarihi,
                        askerlik_durumu,
                        tecil_nedeni,
                        sakatlik_durumu,
                        medeni_durum,
                        cocuk_sayisi,
                        kan_grubu,
                        ehliyet,
                        kizlik_soyadi,
                        rapor_aldigi_gun_sayisi,
                        izinli_gun_sayisi,
                        servis_kullanimi}, this.personel_kayitOperationCompleted, userState);
        }
        
        private void Onpersonel_kayitOperationCompleted(object arg) {
            if ((this.personel_kayitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.personel_kayitCompleted(this, new personel_kayitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KisiDondurad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KisiDondurad(string ad) {
            object[] results = this.Invoke("KisiDondurad", new object[] {
                        ad});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void KisiDonduradAsync(string ad) {
            this.KisiDonduradAsync(ad, null);
        }
        
        /// <remarks/>
        public void KisiDonduradAsync(string ad, object userState) {
            if ((this.KisiDonduradOperationCompleted == null)) {
                this.KisiDonduradOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKisiDonduradOperationCompleted);
            }
            this.InvokeAsync("KisiDondurad", new object[] {
                        ad}, this.KisiDonduradOperationCompleted, userState);
        }
        
        private void OnKisiDonduradOperationCompleted(object arg) {
            if ((this.KisiDonduradCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KisiDonduradCompleted(this, new KisiDonduradCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KisiDondurtc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KisiDondurtc(string tc_kimlik_no) {
            object[] results = this.Invoke("KisiDondurtc", new object[] {
                        tc_kimlik_no});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void KisiDondurtcAsync(string tc_kimlik_no) {
            this.KisiDondurtcAsync(tc_kimlik_no, null);
        }
        
        /// <remarks/>
        public void KisiDondurtcAsync(string tc_kimlik_no, object userState) {
            if ((this.KisiDondurtcOperationCompleted == null)) {
                this.KisiDondurtcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKisiDondurtcOperationCompleted);
            }
            this.InvokeAsync("KisiDondurtc", new object[] {
                        tc_kimlik_no}, this.KisiDondurtcOperationCompleted, userState);
        }
        
        private void OnKisiDondurtcOperationCompleted(object arg) {
            if ((this.KisiDondurtcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KisiDondurtcCompleted(this, new KisiDondurtcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KisiDondurpers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet KisiDondurpers(string personel_no) {
            object[] results = this.Invoke("KisiDondurpers", new object[] {
                        personel_no});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void KisiDondurpersAsync(string personel_no) {
            this.KisiDondurpersAsync(personel_no, null);
        }
        
        /// <remarks/>
        public void KisiDondurpersAsync(string personel_no, object userState) {
            if ((this.KisiDondurpersOperationCompleted == null)) {
                this.KisiDondurpersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKisiDondurpersOperationCompleted);
            }
            this.InvokeAsync("KisiDondurpers", new object[] {
                        personel_no}, this.KisiDondurpersOperationCompleted, userState);
        }
        
        private void OnKisiDondurpersOperationCompleted(object arg) {
            if ((this.KisiDondurpersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KisiDondurpersCompleted(this, new KisiDondurpersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KisiSil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KisiSil(string personel_no) {
            this.Invoke("KisiSil", new object[] {
                        personel_no});
        }
        
        /// <remarks/>
        public void KisiSilAsync(string personel_no) {
            this.KisiSilAsync(personel_no, null);
        }
        
        /// <remarks/>
        public void KisiSilAsync(string personel_no, object userState) {
            if ((this.KisiSilOperationCompleted == null)) {
                this.KisiSilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKisiSilOperationCompleted);
            }
            this.InvokeAsync("KisiSil", new object[] {
                        personel_no}, this.KisiSilOperationCompleted, userState);
        }
        
        private void OnKisiSilOperationCompleted(object arg) {
            if ((this.KisiSilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KisiSilCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KisiGuncelle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KisiGuncelle(
                    string tc_kimlik_no, 
                    string ad, 
                    string soyad, 
                    string dogum_yeri, 
                    string dogum_tarihi, 
                    string cinsiyet, 
                    string uyruk, 
                    string unvan, 
                    string personel_no, 
                    string ev_telefonu, 
                    string cep_telefonu, 
                    string e_posta, 
                    string il, 
                    string ilce, 
                    string adres, 
                    string ise_giris_tarihi, 
                    string firma, 
                    string sube, 
                    string calistigi_birim, 
                    string sigorta_sicil_no, 
                    string vergi_numarasi, 
                    string vergi_dairesi, 
                    string banka, 
                    string banka_subesi, 
                    string banka_hesap_no, 
                    string ilkokul_adi, 
                    string ilkokul_baslama_tarihi, 
                    string ilkokul_mezun_olma_tarihi, 
                    string lise_adi, 
                    string lise_baslama_tarihi, 
                    string lise_mezun_olma_tarihi, 
                    string universite_adi, 
                    string bolumu, 
                    string uni_baslama_tarihi, 
                    string uni_mezun_olma_tarihi, 
                    string egitim_adi, 
                    string egitim_bilgi, 
                    string egitim_baslama_tarihi, 
                    string egitim_bitirme_tarihi, 
                    string isten_ayrilma_nedeni, 
                    string isten_ayrilma_tarihi, 
                    string askerlik_durumu, 
                    string tecil_nedeni, 
                    string sakatlik_durumu, 
                    string medeni_durum, 
                    string cocuk_sayisi, 
                    string kan_grubu, 
                    string ehliyet, 
                    string kizlik_soyadi, 
                    string rapor_aldigi_gun_sayisi, 
                    string izinli_gun_sayisi, 
                    string servis_kullanimi) {
            object[] results = this.Invoke("KisiGuncelle", new object[] {
                        tc_kimlik_no,
                        ad,
                        soyad,
                        dogum_yeri,
                        dogum_tarihi,
                        cinsiyet,
                        uyruk,
                        unvan,
                        personel_no,
                        ev_telefonu,
                        cep_telefonu,
                        e_posta,
                        il,
                        ilce,
                        adres,
                        ise_giris_tarihi,
                        firma,
                        sube,
                        calistigi_birim,
                        sigorta_sicil_no,
                        vergi_numarasi,
                        vergi_dairesi,
                        banka,
                        banka_subesi,
                        banka_hesap_no,
                        ilkokul_adi,
                        ilkokul_baslama_tarihi,
                        ilkokul_mezun_olma_tarihi,
                        lise_adi,
                        lise_baslama_tarihi,
                        lise_mezun_olma_tarihi,
                        universite_adi,
                        bolumu,
                        uni_baslama_tarihi,
                        uni_mezun_olma_tarihi,
                        egitim_adi,
                        egitim_bilgi,
                        egitim_baslama_tarihi,
                        egitim_bitirme_tarihi,
                        isten_ayrilma_nedeni,
                        isten_ayrilma_tarihi,
                        askerlik_durumu,
                        tecil_nedeni,
                        sakatlik_durumu,
                        medeni_durum,
                        cocuk_sayisi,
                        kan_grubu,
                        ehliyet,
                        kizlik_soyadi,
                        rapor_aldigi_gun_sayisi,
                        izinli_gun_sayisi,
                        servis_kullanimi});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KisiGuncelleAsync(
                    string tc_kimlik_no, 
                    string ad, 
                    string soyad, 
                    string dogum_yeri, 
                    string dogum_tarihi, 
                    string cinsiyet, 
                    string uyruk, 
                    string unvan, 
                    string personel_no, 
                    string ev_telefonu, 
                    string cep_telefonu, 
                    string e_posta, 
                    string il, 
                    string ilce, 
                    string adres, 
                    string ise_giris_tarihi, 
                    string firma, 
                    string sube, 
                    string calistigi_birim, 
                    string sigorta_sicil_no, 
                    string vergi_numarasi, 
                    string vergi_dairesi, 
                    string banka, 
                    string banka_subesi, 
                    string banka_hesap_no, 
                    string ilkokul_adi, 
                    string ilkokul_baslama_tarihi, 
                    string ilkokul_mezun_olma_tarihi, 
                    string lise_adi, 
                    string lise_baslama_tarihi, 
                    string lise_mezun_olma_tarihi, 
                    string universite_adi, 
                    string bolumu, 
                    string uni_baslama_tarihi, 
                    string uni_mezun_olma_tarihi, 
                    string egitim_adi, 
                    string egitim_bilgi, 
                    string egitim_baslama_tarihi, 
                    string egitim_bitirme_tarihi, 
                    string isten_ayrilma_nedeni, 
                    string isten_ayrilma_tarihi, 
                    string askerlik_durumu, 
                    string tecil_nedeni, 
                    string sakatlik_durumu, 
                    string medeni_durum, 
                    string cocuk_sayisi, 
                    string kan_grubu, 
                    string ehliyet, 
                    string kizlik_soyadi, 
                    string rapor_aldigi_gun_sayisi, 
                    string izinli_gun_sayisi, 
                    string servis_kullanimi) {
            this.KisiGuncelleAsync(tc_kimlik_no, ad, soyad, dogum_yeri, dogum_tarihi, cinsiyet, uyruk, unvan, personel_no, ev_telefonu, cep_telefonu, e_posta, il, ilce, adres, ise_giris_tarihi, firma, sube, calistigi_birim, sigorta_sicil_no, vergi_numarasi, vergi_dairesi, banka, banka_subesi, banka_hesap_no, ilkokul_adi, ilkokul_baslama_tarihi, ilkokul_mezun_olma_tarihi, lise_adi, lise_baslama_tarihi, lise_mezun_olma_tarihi, universite_adi, bolumu, uni_baslama_tarihi, uni_mezun_olma_tarihi, egitim_adi, egitim_bilgi, egitim_baslama_tarihi, egitim_bitirme_tarihi, isten_ayrilma_nedeni, isten_ayrilma_tarihi, askerlik_durumu, tecil_nedeni, sakatlik_durumu, medeni_durum, cocuk_sayisi, kan_grubu, ehliyet, kizlik_soyadi, rapor_aldigi_gun_sayisi, izinli_gun_sayisi, servis_kullanimi, null);
        }
        
        /// <remarks/>
        public void KisiGuncelleAsync(
                    string tc_kimlik_no, 
                    string ad, 
                    string soyad, 
                    string dogum_yeri, 
                    string dogum_tarihi, 
                    string cinsiyet, 
                    string uyruk, 
                    string unvan, 
                    string personel_no, 
                    string ev_telefonu, 
                    string cep_telefonu, 
                    string e_posta, 
                    string il, 
                    string ilce, 
                    string adres, 
                    string ise_giris_tarihi, 
                    string firma, 
                    string sube, 
                    string calistigi_birim, 
                    string sigorta_sicil_no, 
                    string vergi_numarasi, 
                    string vergi_dairesi, 
                    string banka, 
                    string banka_subesi, 
                    string banka_hesap_no, 
                    string ilkokul_adi, 
                    string ilkokul_baslama_tarihi, 
                    string ilkokul_mezun_olma_tarihi, 
                    string lise_adi, 
                    string lise_baslama_tarihi, 
                    string lise_mezun_olma_tarihi, 
                    string universite_adi, 
                    string bolumu, 
                    string uni_baslama_tarihi, 
                    string uni_mezun_olma_tarihi, 
                    string egitim_adi, 
                    string egitim_bilgi, 
                    string egitim_baslama_tarihi, 
                    string egitim_bitirme_tarihi, 
                    string isten_ayrilma_nedeni, 
                    string isten_ayrilma_tarihi, 
                    string askerlik_durumu, 
                    string tecil_nedeni, 
                    string sakatlik_durumu, 
                    string medeni_durum, 
                    string cocuk_sayisi, 
                    string kan_grubu, 
                    string ehliyet, 
                    string kizlik_soyadi, 
                    string rapor_aldigi_gun_sayisi, 
                    string izinli_gun_sayisi, 
                    string servis_kullanimi, 
                    object userState) {
            if ((this.KisiGuncelleOperationCompleted == null)) {
                this.KisiGuncelleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKisiGuncelleOperationCompleted);
            }
            this.InvokeAsync("KisiGuncelle", new object[] {
                        tc_kimlik_no,
                        ad,
                        soyad,
                        dogum_yeri,
                        dogum_tarihi,
                        cinsiyet,
                        uyruk,
                        unvan,
                        personel_no,
                        ev_telefonu,
                        cep_telefonu,
                        e_posta,
                        il,
                        ilce,
                        adres,
                        ise_giris_tarihi,
                        firma,
                        sube,
                        calistigi_birim,
                        sigorta_sicil_no,
                        vergi_numarasi,
                        vergi_dairesi,
                        banka,
                        banka_subesi,
                        banka_hesap_no,
                        ilkokul_adi,
                        ilkokul_baslama_tarihi,
                        ilkokul_mezun_olma_tarihi,
                        lise_adi,
                        lise_baslama_tarihi,
                        lise_mezun_olma_tarihi,
                        universite_adi,
                        bolumu,
                        uni_baslama_tarihi,
                        uni_mezun_olma_tarihi,
                        egitim_adi,
                        egitim_bilgi,
                        egitim_baslama_tarihi,
                        egitim_bitirme_tarihi,
                        isten_ayrilma_nedeni,
                        isten_ayrilma_tarihi,
                        askerlik_durumu,
                        tecil_nedeni,
                        sakatlik_durumu,
                        medeni_durum,
                        cocuk_sayisi,
                        kan_grubu,
                        ehliyet,
                        kizlik_soyadi,
                        rapor_aldigi_gun_sayisi,
                        izinli_gun_sayisi,
                        servis_kullanimi}, this.KisiGuncelleOperationCompleted, userState);
        }
        
        private void OnKisiGuncelleOperationCompleted(object arg) {
            if ((this.KisiGuncelleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KisiGuncelleCompleted(this, new KisiGuncelleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PersonelBilgilerini_AlCompletedEventHandler(object sender, PersonelBilgilerini_AlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonelBilgilerini_AlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PersonelBilgilerini_AlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void personel_kayitCompletedEventHandler(object sender, personel_kayitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class personel_kayitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal personel_kayitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KisiDonduradCompletedEventHandler(object sender, KisiDonduradCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KisiDonduradCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KisiDonduradCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KisiDondurtcCompletedEventHandler(object sender, KisiDondurtcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KisiDondurtcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KisiDondurtcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KisiDondurpersCompletedEventHandler(object sender, KisiDondurpersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KisiDondurpersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KisiDondurpersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KisiSilCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KisiGuncelleCompletedEventHandler(object sender, KisiGuncelleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KisiGuncelleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KisiGuncelleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591